# Generated by Django 5.1.4 on 2024-12-21 20:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='../default_profile_jx7eer', max_length=255, verbose_name='image'),
        ),
    ]
