# Generated by Django 5.1.4 on 2024-12-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dfi7tw6ox/image/upload/v1734783594/default_profile_jx7eer.jpg', upload_to='images/'),
        ),
    ]
